FROM python:3.8-slim-bullseye

ENV PYTHONPATH=/app

WORKDIR /app
COPY . /app



RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; \
    then \
      pip install --upgrade pip; \
    else \
      pip install kaldi_native_fbank-1.15-cp38-cp38-manylinux_2_17_arm64.whl; \
    fi \
    && pip install -r /app/requirements-cpu.txt -i https://pypi.org/simple \
    && rm -rf ~/.cache/pip


ENTRYPOINT ["python", "backend/app.py"]