FROM python:3.8-slim-bullseye

RUN export DEBIAN_FRONTEND=noninteractive &&\
    echo "deb https://mirrors.tencent.com/debian/ bullseye main non-free contrib" >/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb https://mirrors.tencent.com/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian-security/ bullseye-security main" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye-backports main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src https://mirrors.tencent.com/debian/ bullseye-updates main non-free contrib" >>/etc/apt/sources.list \
    && rm -rf /var/lib/apt/lists/*

ENV VENV="paraformer"
ENV PATH="${PATH}:${VENV}/bin"
ENV PYTHONPATH=/app


WORKDIR /app
COPY . /app

RUN python3 -m venv $VENV \
    && $VENV/bin/pip install --upgrade pip -i http://mirrors.cloud.tencent.com/pypi/simple --trusted-host mirrors.cloud.tencent.com \
    && $VENV/bin/pip install -r /app/requirements-cpu.txt -i http://mirrors.cloud.tencent.com/pypi/simple --trusted-host mirrors.cloud.tencent.com\
    && rm -rf ~/.cache/pip



ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:9000", "--workers", "1", "--timeout", "0", "backend.app:app", "-k", "uvicorn.workers.UvicornWorker"]