# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offlineASR.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10offlineASR.proto\x12\nofflineASR\"=\n\x07Request\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"<\n\x08Response\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t2?\n\x03\x41SR\x12\x38\n\tRecognize\x12\x13.offlineASR.Request\x1a\x14.offlineASR.Response\"\x00\x42\x16\n\x07\x65x.grpc\xa2\x02\nofflineASRb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'offlineASR_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007ex.grpc\242\002\nofflineASR'
  _REQUEST._serialized_start=32
  _REQUEST._serialized_end=93
  _RESPONSE._serialized_start=95
  _RESPONSE._serialized_end=155
  _ASR._serialized_start=157
  _ASR._serialized_end=220
# @@protoc_insertion_point(module_scope)
